### ISSUE TITLE
Duplicate player frames

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#113]
Some parsed demo files contain duplicated player frames. It seems to occur quite rarely, but in multiple demos. I manually checked it in two demos and both times both frames were completely identical.

Example:

![duplicates](https://user-images.githubusercontent.com/85845200/149707279-b872c63a-c034-4f12-a67a-17a375113333.png)

Demo link:

https://www.dropbox.com/s/7ls39izqbu01tgw/003489552203050385434_0816354478.dem?dl=0

Can provide more demos if needed.

**Comment by pnxenopoulos** [comment]
Added a check in the frames parsing code to only add players who are not in the player list. #117

**Comment by adbok001** [comment]
This seems to still be happening

**Comment by pnxenopoulos** [comment]
What are your parsing parameters?

**Comment by adbok001** [comment]
Only `parse_rate=1` and `buy_style="csgo"`

**Comment by pnxenopoulos** [comment]
This appears to just have a frame added twice. I added some code to ensure that if the previous frame has the same tick as the current frame, then not add it. #129
