### ISSUE TITLE
Add `distance` and `isTeamDamage` keys to `damage` objects

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#114]
All `kills` objects have a `distance` and `isTeamKill` key, this could be easily added to `damage` objects as well. Currently it's easy to calculate them yourself with the current `damage` keys (player positions and sides), but direct keys would more convenient.
Maybe it would need another key, `isOwnDamage` or `isSelfDamage`, similar to `isSuicide` in `kills`, or you let it count as `isTeamDamage` as well.

**Comment by pnxenopoulos** [comment]
Team damage on damage events is now set to a bool named `isFriendlyFire` and distance is `distance`.

Ref PR: #117
