### ISSUE TITLE
Add `noScope` key to `damage` and `weaponFire` objects

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#115]
Equivalent to the `noScope` key in every `kill` object, a `noScope` key could be added to `damage` and `weaponFire` objects as well - would be useful for my current project.

**Comment by pnxenopoulos** [comment]
Added `zoomLevel` for damage and weapon fire events. It is an int that refers to the zoom level of the gun. 1 = no zoom, 2 = half zoom, 3 = full zoom.

From Markus' documentation:
"Only weapons with scopes have a valid zoom level."

Ref PR: #117

**Comment by pnxenopoulos** [comment]
Edit, the scale is 0,1,2
