### ISSUE TITLE
Add `isWallbang` key to `damage` objects

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#116]
Equivalent to the `isWallbang` key for every `kill` object, it could be added to `damage` objects as well. This might be tricky as I imagine the `isWallbang` key for kills is extracted from the killfeed (?), similar to #35. But if it's possible, it would be useful for my current project.

**Comment by pnxenopoulos** [comment]
Your intuition is correct -- unfortunately this isn't really available for damage
