### ISSUE TITLE
Missing playerFrames for single ticks

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#119]
I noticed that, in some demos, playerFrames are missing for single ticks. They are missing for all players, and only for a single tick. I used `parse_rate = 1`, so all frames should be parsed (every 2nd tick as it's a GOTV demo). I manually confirmed it in two demos, but there are more.

Example:

![missing_frame](https://user-images.githubusercontent.com/85845200/149868986-d98ede9a-b8d2-4191-8fa9-dabcb6118d1f.PNG)

`tick 104934` -> All player frames available
`tick 104936` -> No player frames available
`tick 104938` -> All player frames available

Demo link:

https://www.dropbox.com/s/k6ms6ebl1vstbl5/003486831536689381471_0732641554.dem?dl=0

Can provide more demos if needed.

**Comment by adbok001** [comment]
Confirmed for this demo that the missing tick is present ingame when watching the demo

**Comment by pnxenopoulos** [comment]
There is no `FrameDone` event at that tick in the demo, thus, that is why there is no frame in the parsed data.
