### ISSUE TITLE
Add newer kill feed indicators to parsed kills 

### ISSUE THREAD

**Issue by cameronshinn** [pnxenopoulos/csgo#12]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a column to the kills data indicating if a kill was a blind kill, no-scope and/or through a smoke. I am making the assumption that since it's a part of the kill feed then it is determined by the game engine and would be easy to parse.

**Describe alternatives you've considered**
Blind kills could be determined looking at the times players were flashed, but no-scope and through smoke kills are impossible to determine.

**Additional context**
Update that implemented this feature into the game is in this [blog post](https://blog.counter-strike.net/index.php/2020/05/30002/).
![image](https://user-images.githubusercontent.com/39427662/119453711-913e1200-bcec-11eb-8865-9986f72b1423.png)

**Comment by pnxenopoulos** [comment]
Hi @cameronshinn, thanks for your feature request. We use Markus' library to parse ([https://github.com/markus-wa/demoinfocs-golang](https://github.com/markus-wa/demoinfocs-golang)). Correct me if I'm wrong, but I can think of three situations: flashes, smokes, no-scopes. These three attributes are not included in the parsed Kill events in Markus' parser. However, we may be able to calculate some of them.

1. FLASHES: I believe getting the victim/killer's flashed information should be straightforward. There is an `IsBlinded` method we can use from Markus' library. 
2. SMOKES/NO-SCOPES: I'm not sure exactly how to approach these. For no-scopes, we can look at if a player is scoped in during the kill, but I'm not sure that will be the case. Need to investigate. Finding through-smoke kills might be harder, but one way could be keeping track of current round smokes and drawing a radius around it and drawing a line between the killer and victim. 

As 1 is much easier to implement and more concrete than 2, I will include it in a future release. Need to think more about 2.

**Comment by cameronshinn** [comment]
I was more wondering if the data was already there in the demo since the game already determines those things itself. If it's dependent on the go parser maybe I'd be better off making an issue in their repo?

**Comment by AKaravas** [comment]
@pnxenopoulos the author updated the package and is now available
https://github.com/markus-wa/demoinfocs-golang/issues/293

**Comment by pnxenopoulos** [comment]
@AKaravas fantastic, saves me the time, thank you. I can wrap this feature up this week.

**Comment by AKaravas** [comment]
Thank you very much

**Comment by markus-wa** [comment]
:wave:

@pnxenopoulos for future reference a good way to check what's easily available is AlliedModders event pages:
- https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#player_death
- https://wiki.alliedmods.net/Generic_Source_Server_Events
- https://wiki.alliedmods.net/Generic_Source_Events

:warning: note that not all events are in demos (most are probably not) 

but for the ones that are there the pages indicate what info is there (e.g. `player_death.thrusmoke`)
If something important is missing from demoinfocs-golang that is on the event pages do let me know as it should be an easy addition. you can also use `GenericGameEvent` to capture the raw event including all this data, but they'll be much more painful to work with than the abstracted events.

cool project btw! :rocket:

**Comment by pnxenopoulos** [comment]
@cameronshinn should be in the most recent commit, try reinstalling.

**Comment by cameronshinn** [comment]
@pnxenopoulos awesome thanks, I'll check it out!
