### ISSUE TITLE
Incorrect clock_time format after C4 kill

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/csgo#120]
**Describe the bug**
A kill after a C4 explosion has an incorrect format : 0-1:59

**To Reproduce**
1. Go to demo https://www.hltv.org/matches/2352998/big-vs-esuba-v4-future-sports-festival-2021
2. Parse and clean rounds
3. Scroll down to round 2
4. See error on the last kill

**Expected behavior**
A correct clock time

**Screenshots**
![ClockTime](https://user-images.githubusercontent.com/92644057/149971347-dc2b6a63-43fe-4286-a4f7-4f77f82d1ec8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : N/A
 - Version : N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pnxenopoulos** [comment]
Appears to be fixed in #121
