### ISSUE TITLE
Error with 'ammoInMagazine' Field

### ISSUE THREAD

**Issue by arjun-22** [pnxenopoulos/csgo#127]
In the weapons dictionaries within each frame dictionary within each round dictionary, I found the following error:
{'weaponName': 'C4',
  'weaponClass': 'Equipment',
  'ammoInMagazine': -1,
  'ammoInReserve': 0}]

The field 'ammoInMagazine' should not equal -1.

**Comment by arjun-22** [comment]
The demofile is the same as the one used in the Basic CSGO Analysis example notebook:  https://www.hltv.org/matches/2337844/astralis-vs-liquid-blast-pro-series-global-final-2019 (nuke)

**Comment by pnxenopoulos** [comment]
Fixed for both frames and weaponfires (not sure if that was a problem, but "fixed" anyways).

Also, there's now a `hasBomb` flag.

All in #128
