### ISSUE TITLE
Competitive Rank

### ISSUE THREAD

**Issue by AKaravas** [pnxenopoulos/csgo#13]
I would like to add the ranks of each player when i get the parsed json file. I asked the author of  the demoinfocs-golang if this is implemented and he said that it is already there. [Code](https://pkg.go.dev/github.com/markus-wa/demoinfocs-golang/v2@v2.8.1/pkg/demoinfocs/events#RankUpdate)

**Describe the solution you'd like**
Maybe at the end of the array the relevant rank information for each player

**Comment by pnxenopoulos** [comment]
Looks simple enough to add. What I'll probably do is create some sort of top-level field called `RankUpdates` and put the info there. I'll link you to a commit when I make it. Should be this week.

**Comment by AKaravas** [comment]
alright! Can't wait :) Thank you

**Comment by pnxenopoulos** [comment]
Hi @AKaravas, sorry for coming to this so late. Check the 9543c4e (latest) on the `dev` branch. I still need to test, but this was a quick addition. If you have the time, it would be helpful to test on some MM demos you may have laying around.

**Comment by AKaravas** [comment]
@pnxenopoulos i have a lot on my plate right now, but i will try to find the time to do it. As far i understand the implmentation (project built) has been changed as well right?

**Comment by pnxenopoulos** [comment]
Fixed the errors. The update is now in the `dev` branch, and I tested it on a MM demofile. I will need to add some documentation/maybe some translation functions for the ranks, which are currently integers. Once I add that, I can pull the change into the `main` branch.

**Comment by pnxenopoulos** [comment]
Alright, it's all finished in the `dev` branch (latest commit 16a03fb). The ranks are in a top-level field called "MatchmakingRanks", which is a list. Here's an example:

```
"MatchmakingRanks": [
  {
   "SteamID": 76561199085390741,
   "RankChange": 0,
   "RankOld": "Gold Nova Master",
   "RankNew": "Gold Nova Master",
   "WinCount": 380
  },
  {
   "SteamID": 76561198835013624,
   "RankChange": 0,
   "RankOld": "Gold Nova 2",
   "RankNew": "Gold Nova 2",
   "WinCount": 229
  },
  {
   "SteamID": 76561198386529440,
   "RankChange": 0,
   "RankOld": "Silver Elite Master",
   "RankNew": "Silver Elite Master",
   "WinCount": 914
  },
  {
   "SteamID": 76561197999389679,
   "RankChange": 0,
   "RankOld": "Silver Elite Master",
   "RankNew": "Silver Elite Master",
   "WinCount": 310
  },
  {
   "SteamID": 76561198292717420,
   "RankChange": 0,
   "RankOld": "Gold Nova 1",
   "RankNew": "Gold Nova 1",
   "WinCount": 92
  },
  {
   "SteamID": 76561198123487907,
   "RankChange": 0,
   "RankOld": "Gold Nova 3",
   "RankNew": "Gold Nova 3",
   "WinCount": 106
  },
  {
   "SteamID": 76561198123584931,
   "RankChange": 0,
   "RankOld": "Gold Nova 3",
   "RankNew": "Gold Nova 3",
   "WinCount": 81
  },
  {
   "SteamID": 76561198142119366,
   "RankChange": 1,
   "RankOld": "Gold Nova 3",
   "RankNew": "Gold Nova Master",
   "WinCount": 665
  },
  {
   "SteamID": 76561198090370957,
   "RankChange": 0,
   "RankOld": "Gold Nova 3",
   "RankNew": "Gold Nova 3",
   "WinCount": 515
  },
  {
   "SteamID": 76561198835616478,
   "RankChange": 0,
   "RankOld": "Gold Nova 3",
   "RankNew": "Gold Nova 3",
   "WinCount": 210
  }
 ]
```
