### ISSUE TITLE
Missing frames from _parse_player_frames

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#16]
I noticed that in the demo I parsed that after calling _parse_player_frames there are rounds with only player frames from one team, missing the other team completely.
Rounds 1-18 are fine and have both teams, round 19 only got the first few frames for both teams and missing the whole CT side after that.
All other rounds after that until the game ends (rounds 20-22) are missing the whole CT side frames as well.

I can provide the demo if needed. As return_type I used "list" and parsed with parse_rate=1.
I checked the json file and it looks like the information is correctly parsed there.

**Comment by pnxenopoulos** [comment]
Hi @adbok001, can you confirm two things:

1) Are you using the most recent version of the library?
2) Do you have a link to the demo, along with any more information about it?

**Comment by adbok001** [comment]
Yeah, using the newest version
I tried a second demo now, here again the last two rounds are missing for CT side (RoundNum=23 and 24), so I imagine it's in every (matchmaking) demo.
I uploaded it here as the original download link expired - Valve apparently changed it to deleting them after a week instead of a month:

https://easyupload.io/h64yre

**Comment by adbok001** [comment]
@pnxenopoulos Hey, were you able to reproduce this?

**Comment by pnxenopoulos** [comment]
Hi @adbok001, just took a look now. I was **unable** to reproduce the error. Using a parse rate of 128, I get 12 frames for each of the last two rounds and each round has frames. I also tried the parser on some matchmaking games of my own. Was there anything weird about the matches?

**Comment by adbok001** [comment]
Can be fixed with https://github.com/pnxenopoulos/csgo/pull/23

For whatever reason, frames with less than 5 players in a team were completely skipped. I'm sure you had a reason to add this for your analysis of pro matches, but it's unviable for matchmaking games where a lot of people leave.

**Comment by adbok001** [comment]
I saw you added it now. Closing then.
