### ISSUE TITLE
Change the module name to avoid name collisions

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#21]
Currently it's not possible to install both this module and https://github.com/ValvePython/csgo in a clean way due to both having the same module name.
"csgo-parser" or something along that line also describes the project better.

**Comment by pnxenopoulos** [comment]
I think given that the library will expand to include non-parsing capabilities, such as calculating common statistics or visualizing, we will keep the name as `csgo`. You can see this Stack link for info that may help you: [https://stackoverflow.com/questions/27308293/how-to-install-python-package-with-a-different-name-using-pip](https://stackoverflow.com/questions/27308293/how-to-install-python-package-with-a-different-name-using-pip)
