### ISSUE TITLE
Boosting lobbies break the parser

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#24]
It looks like boosting lobby demos break the parsing process:

```
03:35:17 [INFO] Go version>=1.14.0
03:35:17 [INFO] Initialized CSGODemoParser with demofile /home/demos/003489108305295442237_1068538509.dem
03:35:17 [INFO] Setting demo id to 003489108305295442237_1068538509
03:35:17 [WARNING] A parse rate of 1 will parse EVERY tick. This process will be very slow.
03:35:17 [INFO] Setting parse rate to 1
03:35:17 [INFO] Running Golang parser from /home_remote/docker_home/python/lib/python3.9/site-packages/csgo-0.1-py3.9.egg/csgo/parser/
03:35:17 [INFO] Looking for file at /home/demos/003489108305295442237_1068538509.dem
03:35:19 [ERROR] No file produced, error in calling Golang
03:35:19 [ERROR] []
03:35:19 [INFO] Reading in JSON from 003489108305295442237_1068538509.json

FileNotFoundError: [Errno 2] No such file or directory: '/home/003489108305295442237_1068538509.json'
```

The demo is available for another 4 days here:

http://replay182.valve.net/730/003489108305295442237_1068538509.dem.bz2

**Comment by pnxenopoulos** [comment]
Interesting find. The demo file is quite small, can you describe it a bit more? What exactly is a boosting lobby, why is the demo so small, etc.

**Comment by adbok001** [comment]
Well, you can take a look for yourself.
Warmup is played normally, then all five players from one team leave the game and keep rejoining. Looks like the game counts it instantly as a round win if all enemy players left. Then they rejoin and instantly leave again, so the next round is counted as a win.
So probably more of a deranking lobby here it seems.

A different demo of the same procedure, this time on Mirage instead of Office, is correctly parsed tho.

Demo link:

http://replay271.valve.net/730/003489235872266584085_0959478080.dem.bz2

Only other difference I noticed - other than the map - is that in the failing demo all 5 players rejoined on the last round and then left pretty much at the same time.

**Comment by pnxenopoulos** [comment]
I wonder if it makes sense to even accommodate this edge case. Probably nobody will be parsing boosting demofiles. I'm gonna mark as `wontfix` for that reason. However, this is an interesting find. Perhaps it would be useful as a side project to build a quick parser to determine if a demofile is a boosting lobby or not and send it to Valve.
