### ISSUE TITLE
Accuracy of cleaning the rounds?

### ISSUE THREAD

**Issue by mcastrogg** [pnxenopoulos/csgo#25]
Hello, great work so far (Output is nice and clean!), just a quick question regarding the "post-processing" of the rounds. How accurate is the cleaning and then re-ordering of the rounds? I've been working with the go parser and was actually thinking about implementing something similar but was going to use the ScoreUpdated event as one of the central events. Have you run across any demos that when you clean them they spit out incorrect round order/kills etc? This question is mainly focused around demos from HLTV. Thanks.

**Comment by pnxenopoulos** [comment]
Hi @mcastrogg, thanks for checking out the library! I would say there is some resiliency built into the parser to account for weird event sequences. In my experience, the total # of rounds seems to be correct. In older versions, round coverage was an issue. If you come across any incorrect parses, open and issue, it helps a lot.
