### ISSUE TITLE
Add support for maps without 2 bombsites

### ISSUE THREAD

**Issue by pnxenopoulos** [pnxenopoulos/csgo#27]
First identified in #26. Parsing fails on maps that don't have two bombsites (i.e., standard competitive maps). Could be useful for parsing MM demos from mocha, grind, office, etc.

**Comment by adbok001** [comment]
Alright, can confirm that the vast majority of failing demos are from Cache, Ancient, Mocha, Grind, Office and Agency. If hostage maps break the parser, that probably explains #24 as well, as those boosting lobbies mostly use hostage maps (Agency, Office).

So, Cache demos should be parsed correctly now? And Ancient, Mocha and Grind as well, as they are normal defusal maps with two bombsites as well?
If it fails without two bombsites, it should only crash when parsing hostage map demos (or wingman demos, I imagine).

Do you think you will be able to fix this in the next few days? I imagine detecting if a demo is from a hostage map and then just setting all bomb related stuff to null should be easy enough to add and is, at least for me, good enough.
I guess even a correct fix probably is not much more than setting the bomb locations to hostage locations and adding the Agency and Office nav files?

Thanks!

**Comment by adbok001** [comment]
Here's a demo from cs_office, hostage map. Should be available for another ~6 days:

http://replay272.valve.net/730/003508905445945245832_2127855124.dem.bz2

**Comment by pnxenopoulos** [comment]
Parsing works for this one! Closing this issue.
