### ISSUE TITLE
IsTeamkill set to true for all kills in MM demos

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#28]
In [`parse_demo.go, L1357`](https://github.com/pnxenopoulos/csgo/blob/master/csgo/parser/parse_demo.go#L1357) you compare the ClanNames to determine a teamkill. In a matchmaking demo, these are null for both teams in nearly every match.

An easy fix should be to check for the team side (CT or T) rather than the clan names

**Comment by pnxenopoulos** [comment]
Yes, you're totally right. Thanks for calling this out. Should be fixed now.
