### ISSUE TITLE
Parsing fails if the game gets surrendered after 5 rounds

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#29]
It looks like parsing fails if the match gets surrendered after five rounds. I've seen only 5-0 and 4-1 score lines, so maybe it's specific to only these scores. Error is an out of range error at [`parse_demo.go, L1759`](https://github.com/pnxenopoulos/csgo/blob/master/csgo/parser/parse_demo.go#L1759).
I added four of these demos [here](https://github.com/adbok001/demos) again.

Error:

panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
main.main()
	/home/csgo/parser/parse_demo.go:1759 +0x4030
exit status 2

**Comment by pnxenopoulos** [comment]
Fixed in 5a36435, currently in `dev`, will merge into `main` in a few days/1 week.
