### ISSUE TITLE
de_mocha demos fail to parse

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#30]
It looks like Mocha demos are still failing to parse. Same error like #26 at [`parse_demo.go, L1735`](https://github.com/pnxenopoulos/csgo/blob/master/csgo/parser/parse_demo.go#L1735).
So maybe something went wrong when adding the nav file for Mocha, because it worked for Cache, Ancient and Grind - these demos are getting parsed fine now.
This is not the same error as #27, Mocha is a normal 5v5 defusal map.
I added three de_mocha demos [here](https://github.com/adbok001/demos) (the .bz2 zipped demos).

Error:

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
	/home/csgo/parser/parse_demo.go:1735 +0x4085
exit status 2

**Comment by pnxenopoulos** [comment]
I looked into this a bit more. I think it may be a problem with the `.nav` file. I'll keep you updated.

**Comment by pnxenopoulos** [comment]
Seems to work with the most recent update. I tried one of your mocha demos and it parsed. Let me know if you still run into errors.
