### ISSUE TITLE
Error converting json to df when round has no Flashes

### ISSUE THREAD

**Issue by parobo** [pnxenopoulos/csgo#6]
This is my first issue report on github, please excuse mistakes that I make in the reporting style.
**Describe the bug**
The DemoParser.parse() with return_type='df' throughs a TypeError: 'NoneType' object is not iterable.
This seems to happen when there are no flash events in a round.
**To Reproduce**
The problem occurs e.g. with the following demo: https://www.hltv.org/download/demo/61730, in particular the second map. But I think it occurs more generally with any demo that does contain any rounds where no Flashes are used.
1. Download the demofile (https://www.hltv.org/download/demo/61730) from hltv.
2. initialize DemoParser
3. Run parse(return_type='df') on the demoparser

**Expected behavior**
Produce the regular DataFrame for flashes.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Brave
 - Version: 1.18.70

**Additional context**
I think the issue is simply that there is no condition for rounds without flashes. Should be possible to fix by adding in a condition for when r['Flashes'] is not None like there already is one for BombEvents.

**Comment by pnxenopoulos** [comment]
Hi @parobo, thanks for bringing this issue to my attention and for filing a very nice issue report. I was able to reproduce the bug by using the most recent version of `csgo`. 

I've updated the library to add the checks you suggest, not only to the flash events but also grenade, damage, and kill events. Using the demofile you mentioned, these updates seem to address the problem.

You can reinstall the library by running `pip uninstall csgo` and then using the same install instructions (`python setup.py install` on the most recent version of the library). 

I'm going to go ahead and close this issue, but feel free to reopen it if you have trouble reinstalling or the problem appears again.
