### ISSUE TITLE
Old Demos not parseable

### ISSUE THREAD

**Issue by jeremieroche** [pnxenopoulos/csgo#61]
**Describe the bug**
Old Demos are not parseable

**To Reproduce**
Download HLTV demo: https://www.hltv.org/matches/2343604/big-vs-ago-esl-pro-league-season-12-europe
Run the following python script
```
    from csgo.parser import DemoParser
    f = "big-vs-ago-m2-dust2.dem"
    output_file = f.replace("-","_").replace(".dem","_01")
    print(output_file)
    demo_parser = DemoParser(demofile=f, demo_id=output_file, parse_rate=128)
    data = demo_parser.parse()
```

**Expected behavior**

Parsed Demo

**Screenshots**

**Additional context**

Trying to backfill old demos under the v1 parser

**Comment by pnxenopoulos** [comment]
Fixed in da99ef2
