### ISSUE TITLE
Nav Mesh Area/Tile Plotting

### ISSUE THREAD

**Issue by adisujithkumar** [pnxenopoulos/csgo#64]
**Is your feature request related to a problem? Please describe.**
No not really a problem; just a cool feature I think that could be useful

**Describe the solution you'd like**
Built-in functionality to plot by nav tile. For example if one wanted to plot all the nav tiles the CT team is occupying, this hypothetical function could help out (user wouldn't have to manually plot the pixels in the tile).

**Describe alternatives you've considered**
Plotting rectangles with matplotlib

**Comment by pnxenopoulos** [comment]
The rectangles from matplotlib should work, using the info from `MAP_NAV`. We can work on a solution

**Comment by pnxenopoulos** [comment]
The rectangles from matplotlib should work, using the info from `MAP_NAV`. We can work on a solution

**Comment by pnxenopoulos** [comment]
Moving into larger nav issue. Probably not needed at the moment.
