### ISSUE TITLE
JSON pretty print after using clean_rounds method

### ISSUE THREAD

**Issue by kenmareirl** [pnxenopoulos/csgo#69]
**Is your feature request related to a problem? Please describe.**
Not at all. With the new method clean_rounds the json is not pretty print, there are no indentation anymore.

**Describe the solution you'd like**
Fix json.dump(self.json, fp) in demoparser.py's write_json method to something like json.dumps(simplejson.loads(output), indent=4)

**Describe alternatives you've considered**
Format with manual (and pretty easy) action

**Additional context**
N/A

**Comment by pnxenopoulos** [comment]
Fixed in #77
