### ISSUE TITLE
Add a top-level field containing all players present in the demo

### ISSUE THREAD

**Issue by adbok001** [pnxenopoulos/csgo#96]
Some matchmaking demos do not contain any `matchmakingRanks` list. To check which players are present in the demo, it's needed to cycle through `gameRounds` and `frames`.

A `players` list containing all players (steamID) in the json files would help here.

**Comment by pnxenopoulos** [comment]
I'll leave this for styx to implement. Putting as low priority so we finish #35 first

**Comment by pnxenopoulos** [comment]
Added player connects and disconnects in #102.
